/* DATA DE RESTAURANTES */
var data = [{
  'name': 'Central Restaurante',
  'image': 'assets/images/restaurants/central.jpg',
  'description': 'Central Restaurante es un restaurante peruano ubicado en el distrito de Miraflores (Lima). Central Restaurante es el restaurante principal del chef peruano Virgilio Martínez Véliz y sirve como su taller en la investigación y la integración de insumos indígenos peruanos en la carta de comida del restaurante. El restaurante es conocido por su interpretación contemporánea y presentación de la cocina peruana.1​ Desde el año 2014 al año 2016 , tres años consecutivos , fue clasificado como el mejor restaurante de Latinoamérica por la revista británica ',
  'telephone': '(01) 2428515',
  'address': 'Calle Santa Isabel 376, Miraflores, Lima 15074',
  'web': 'www.centralrestaurante.com.pe',
},
{
  'name': 'Puro Perú Buffet',
  'image': 'assets/images/restaurants/puro-peru.jpg',
  'description': 'El prestigioso restaurante PURO PERÚ abrió sus puertas en el año 1999 en el tradicional Distrito de Barranco, salió como una nueva propuesta para que nuestros clientes puedan disfrutar de la variedad de sabores que ofrece nuestro Perú, de ahí nace la idea del nombre “PURO PERÚ”.',
  'telephono': '(01) 4770111',
  'address': 'Av. República de Panamá 258, Barranco 15049',
  'web': 'http://www.puroperu.com.pe/es/',
},
{
  'name': 'Wallqa',
  'image': 'assets/images/restaurants/wallqa.jpg',
  'description': 'Wallqa viene del idioma andino  Quechua y significa insignia o medalla, haciendo  referencia a aquellos distintivos que lucían los personajes importantes de la sociedad del Tahuantinsuyo, tal como distingue en gastronomía ser portador del Cordón Azul, Le Cordon Bleu.',
  'telephono': '(01) 2429619',
  'address': 'Av Vasco Núñez de Balboa 530, Miraflores 15074',
  'web': 'www.wallqa.com.pe',
},
{
  'name': 'Saqra',
  'image': 'assets/images/restaurants/saqra.jpg',
  'description': 'Saqra – en esencia – no es un lugar, es un personaje divertido y travieso, que quiere que todos nuestros invitados vivan una experiencia singular, en la que se reencuentren con el niño interior que llevan dentro. Saqra es una versión de nosotros mismos: la más divertida y traviesa, la que nos obliga a cuestionar nuestros límites, la que tiene una risa fácil y contagiosa. Saqra se expresa a través de la pintura y la música. Y la buena comida. Aquella que complace no solo al paladar sino a la vista, al olfato y al tacto.',
  'telephono': '(01) 6508884',
  'address': 'Av. la Paz 646, Miraflores Lima 18',
  'web': 'http://www.saqra.pe/',
},
{
  'name': 'Maido',
  'image': 'assets/images/restaurants/maido.jpg',
  'description': '"En Japón hay muchas formas de decir “bienvenidos”, pero ninguna tiene tanto significado como “Maido”. Esta frase no solo le da el nombre al restaurante; sino que también resume el sentimiento de hacer que cada cliente se sienta en casa."',
  'telephono': '(01) 446 - 2512',
  'address': 'Ubicación: calle San Martín 399 ( Esquina con calle Colón ), Miraflores - Lima, Perú',
  'web': 'http://www.maido.pe/',
},
{
  'name': 'Huaca Pucllana',
  'image': 'assets/images/restaurants/huaca-pucllana.jpg',
  'description': 'Ocurre, pues, que La Huaca Pucllana mantiene con justificado orgullo una filosofía culinaria cuyo concepto fundamental radica en utilizar como base los sabores del Perú, interpretando de acuerdo a las técnicas clásicas de cocina, así como a los estilos contemporáneos y a las exigencias de los paladares más exquisitos. Con el calificado aporte de Arturo Rubio, promotor del restaurant, y de nuestras chefs Marilú Madueño y  Andrea Massaro, el restaurant ofrece una comida renovada cuyo cimiento es la cocina peruana, con su riquísima variedad de productos, llámense pescados de mar, mariscos, o lo que forma el inmenso abanico de vegetales, con todos los colores, texturas y sabores. ',
  'telephono': '01 - 445 4042',
  'address': 'General Borgoño cdra. 8, Huaca Pucllana - Miraflores',
  'web': 'http://www.resthuacapucllana.com/es/',
},
{
  'name': 'ámaz',
  'image': 'assets/images/restaurants/amaz.jpg',
  'description': 'La amazonía es una de las zonas con mayor diversidad y riqueza biológica del planeta. Gran parte de su despensa aún no se ha promovido de manera sostenida en la cocina contemporánea a nivel mundial. ámaZ nace con el fin de llevar al mundo la gastronomía, cultura e insumos de la región amazónica con un enfoque contemporáneo que busca difundir y preservar nuestra despensa.',
  'telephono': '(01) 221 9393 / (01) 221 9880',
  'address': 'Av. La Paz 1079, Miraflores, Lima - Perú',
  'web': 'http://amaz.com.pe/',
},
{
  'name': 'IK - Ivan Kisic',
  'image': 'assets/images/restaurants/ik.jpg',
  'description': 'En IK encontrarás elaboraciones peruanas de autor cuidados en detalle, en donde lo orgánico, la calidad y el respeto hacia los productos conviven para compartir protagonismo. Técnicas de vanguardía y ancestrales se encuentran en un mismo ambiente con el objetivo de sorprender al cliente y mostrarle lo que el Perú y su gente tienen para ofrecer.',
  'telephono': '+511 652 1692',
  'address': 'Calle Elías Aguirre N° 179, Miraflores, Lima 18 Perú',
  'web': 'http://www.ivankisic.pe/',
},
];